(function(){var require=function(file,cwd){var resolved=require.resolve(file,cwd||'/');var mod=require.modules[resolved];if(!mod)throw new Error('Failed to resolve module '+file+', tried '+resolved);var cached=require.cache[resolved];var res=cached?cached.exports:mod();return res;};require.paths=[];require.modules={};require.cache={};require.extensions=[".js",".coffee",".json"];require._core={'assert':true,'events':true,'fs':true,'path':true,'vm':true};require.resolve=(function(){return function(x,cwd){if(!cwd)cwd='/';if(require._core[x])return x;var path=require.modules.path();cwd=path.resolve('/',cwd);var y=cwd||'/';if(x.match(/^(?:\.\.?\/|\/)/)){var m=loadAsFileSync(path.resolve(y,x))||loadAsDirectorySync(path.resolve(y,x));if(m)return m;}
var n=loadNodeModulesSync(x,y);if(n)return n;throw new Error("Cannot find module '"+x+"'");function loadAsFileSync(x){x=path.normalize(x);if(require.modules[x]){return x;}
for(var i=0;i<require.extensions.length;i++){var ext=require.extensions[i];if(require.modules[x+ext])return x+ext;}}
function loadAsDirectorySync(x){x=x.replace(/\/+$/,'');var pkgfile=path.normalize(x+'/package.json');if(require.modules[pkgfile]){var pkg=require.modules[pkgfile]();var b=pkg.browserify;if(typeof b==='object'&&b.main){var m=loadAsFileSync(path.resolve(x,b.main));if(m)return m;}
else if(typeof b==='string'){var m=loadAsFileSync(path.resolve(x,b));if(m)return m;}
else if(pkg.main){var m=loadAsFileSync(path.resolve(x,pkg.main));if(m)return m;}}
return loadAsFileSync(x+'/index');}
function loadNodeModulesSync(x,start){var dirs=nodeModulesPathsSync(start);for(var i=0;i<dirs.length;i++){var dir=dirs[i];var m=loadAsFileSync(dir+'/'+x);if(m)return m;var n=loadAsDirectorySync(dir+'/'+x);if(n)return n;}
var m=loadAsFileSync(x);if(m)return m;}
function nodeModulesPathsSync(start){var parts;if(start==='/')parts=[''];else parts=path.normalize(start).split('/');var dirs=[];for(var i=parts.length-1;i>=0;i--){if(parts[i]==='node_modules')continue;var dir=parts.slice(0,i+1).join('/')+'/node_modules';dirs.push(dir);}
return dirs;}};})();require.alias=function(from,to){var path=require.modules.path();var res=null;try{res=require.resolve(from+'/package.json','/');}
catch(err){res=require.resolve(from,'/');}
var basedir=path.dirname(res);var keys=(Object.keys||function(obj){var res=[];for(var key in obj)res.push(key);return res;})(require.modules);for(var i=0;i<keys.length;i++){var key=keys[i];if(key.slice(0,basedir.length+1)===basedir+'/'){var f=key.slice(basedir.length);require.modules[to+f]=require.modules[basedir+f];}
else if(key===basedir){require.modules[to]=require.modules[basedir];}}};(function(){var process={};var global=typeof window!=='undefined'?window:{};var definedProcess=false;require.define=function(filename,fn){if(!definedProcess&&require.modules.__browserify_process){process=require.modules.__browserify_process();definedProcess=true;}
var dirname=require._core[filename]?'':require.modules.path().dirname(filename);var require_=function(file){var requiredModule=require(file,dirname);var cached=require.cache[require.resolve(file,dirname)];if(cached&&cached.parent===null){cached.parent=module_;}
return requiredModule;};require_.resolve=function(name){return require.resolve(name,dirname);};require_.modules=require.modules;require_.define=require.define;require_.cache=require.cache;var module_={id:filename,filename:filename,exports:{},loaded:false,parent:null};require.modules[filename]=function(){require.cache[filename]=module_;fn.call(module_.exports,require_,module_,module_.exports,dirname,filename,process,global);module_.loaded=true;return module_.exports;};};})();require.define("path",function(require,module,exports,__dirname,__filename,process,global){function filter(xs,fn){var res=[];for(var i=0;i<xs.length;i++){if(fn(xs[i],i,xs))res.push(xs[i]);}
return res;}
function normalizeArray(parts,allowAboveRoot){var up=0;for(var i=parts.length;i>=0;i--){var last=parts[i];if(last=='.'){parts.splice(i,1);}else if(last==='..'){parts.splice(i,1);up++;}else if(up){parts.splice(i,1);up--;}}
if(allowAboveRoot){for(;up--;up){parts.unshift('..');}}
return parts;}
var splitPathRe=/^(.+\/(?!$)|\/)?((?:.+?)?(\.[^.]*)?)$/;exports.resolve=function(){var resolvedPath='',resolvedAbsolute=false;for(var i=arguments.length;i>=-1&&!resolvedAbsolute;i--){var path=(i>=0)?arguments[i]:process.cwd();if(typeof path!=='string'||!path){continue;}
resolvedPath=path+'/'+resolvedPath;resolvedAbsolute=path.charAt(0)==='/';}
resolvedPath=normalizeArray(filter(resolvedPath.split('/'),function(p){return!!p;}),!resolvedAbsolute).join('/');return((resolvedAbsolute?'/':'')+resolvedPath)||'.';};exports.normalize=function(path){var isAbsolute=path.charAt(0)==='/',trailingSlash=path.slice(-1)==='/';path=normalizeArray(filter(path.split('/'),function(p){return!!p;}),!isAbsolute).join('/');if(!path&&!isAbsolute){path='.';}
if(path&&trailingSlash){path+='/';}
return(isAbsolute?'/':'')+path;};exports.join=function(){var paths=Array.prototype.slice.call(arguments,0);return exports.normalize(filter(paths,function(p,index){return p&&typeof p==='string';}).join('/'));};exports.dirname=function(path){var dir=splitPathRe.exec(path)[1]||'';var isWindows=false;if(!dir){return'.';}else if(dir.length===1||(isWindows&&dir.length<=3&&dir.charAt(1)===':')){return dir;}else{return dir.substring(0,dir.length-1);}};exports.basename=function(path,ext){var f=splitPathRe.exec(path)[2]||'';if(ext&&f.substr(-1*ext.length)===ext){f=f.substr(0,f.length-ext.length);}
return f;};exports.extname=function(path){return splitPathRe.exec(path)[3]||'';};exports.relative=function(from,to){from=exports.resolve(from).substr(1);to=exports.resolve(to).substr(1);function trim(arr){var start=0;for(;start<arr.length;start++){if(arr[start]!=='')break;}
var end=arr.length-1;for(;end>=0;end--){if(arr[end]!=='')break;}
if(start>end)return[];return arr.slice(start,end-start+1);}
var fromParts=trim(from.split('/'));var toParts=trim(to.split('/'));var length=Math.min(fromParts.length,toParts.length);var samePartsLength=length;for(var i=0;i<length;i++){if(fromParts[i]!==toParts[i]){samePartsLength=i;break;}}
var outputParts=[];for(var i=samePartsLength;i<fromParts.length;i++){outputParts.push('..');}
outputParts=outputParts.concat(toParts.slice(samePartsLength));return outputParts.join('/');};});require.define("__browserify_process",function(require,module,exports,__dirname,__filename,process,global){var process=module.exports={};process.nextTick=(function(){var canSetImmediate=typeof window!=='undefined'&&window.setImmediate;var canPost=typeof window!=='undefined'&&window.postMessage&&window.addEventListener;if(canSetImmediate){return function(f){return window.setImmediate(f)};}
if(canPost){var queue=[];window.addEventListener('message',function(ev){if(ev.source===window&&ev.data==='browserify-tick'){ev.stopPropagation();if(queue.length>0){var fn=queue.shift();fn();}}},true);return function nextTick(fn){queue.push(fn);window.postMessage('browserify-tick','*');};}
return function nextTick(fn){setTimeout(fn,0);};})();process.title='browser';process.browser=true;process.env={};process.argv=[];process.binding=function(name){if(name==='evals')return(require)('vm')
else throw new Error('No such module. (Possibly not yet loaded)')};(function(){var cwd='/';var path;process.cwd=function(){return cwd};process.chdir=function(dir){if(!path)path=require('path');cwd=path.resolve(dir,cwd);};})();});require.define("/lib/displaygame.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var DisplayBoard,DisplayGame,Game,Layouts,Location,Pieces,Renderer,__bind=function(fn,me){return function(){return fn.apply(me,arguments);};};Renderer=require('./renderer');Game=require('./game');DisplayBoard=require('./displayboard');Layouts=require('./layouts');Pieces=require('./pieces');Location=require('./location');module.exports=DisplayGame=(function(){function DisplayGame(elt){this.draw=__bind(this.draw,this);var _this=this;this.game=new Game(Layouts.traditional);this.renderer=new Renderer(elt);this.board=new DisplayBoard(this.renderer);window.setInterval(this.draw,66);elt.addEventListener('mousemove',function(evt){var rect,x,y,_ref,_ref1;rect=elt.getBoundingClientRect();_ref=[evt.clientX-rect.left,evt.clientY-rect.top],x=_ref[0],y=_ref[1];_ref1=_this.renderer.boardspace(x,y),x=_ref1[0],y=_ref1[1];x=Math.max(Math.min(Math.round(x),8),1);y=Math.max(Math.min(Math.round(y),8),1);return _this.location=new Location(x,y);});elt.addEventListener('mouseout',function(evt){return _this.location=null;});elt.addEventListener('mousedown',function(evt){return _this.draggedpiece=_this.game.board.atloc(_this.location).piece;});elt.addEventListener('mouseup',function(evt){_this.game.move(_this.draggedpiece,_this.game.board.atloc(_this.location));return _this.draggedpiece=null;});}
DisplayGame.prototype.draw=function(){var h,move,p,x,y,_i,_len,_ref,_ref1;this.game.tick();this.board.draw();_ref=this.game.pieces;for(_i=0,_len=_ref.length;_i<_len;_i++){p=_ref[_i];if(p.in_play()){_ref1=[p.location.x,p.location.y],x=_ref1[0],y=_ref1[1];this.renderer.image(x,y,p.img);if(p.cooldown!=null){h=p.cooldown.fraction_remaining();this.renderer.rect(x-0.5,y-0.5,x+0.5,y-0.5+h,'red',0.5);this.renderer.rect(x-0.5,y-0.5+h,x+0.5,y+0.5,'green',0.5);}}}
if(this.game.victor){return this.renderer.text(this.renderer.elt.width/2,this.renderer.elt.height/2,""+this.game.victor+"\nwins!");}else if((this.draggedpiece!=null)&&(this.location!=null)){move={from:this.game.board.cell_of(this.draggedpiece),to:this.game.board.atloc(this.location)};if(this.draggedpiece.valid_move(move)){return this.renderer.image(this.location.x,this.location.y,this.draggedpiece.img,0.5);}}};return DisplayGame;})();}).call(this);});require.define("/lib/renderer.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Renderer;module.exports=Renderer=(function(){function Renderer(elt){this.elt=elt;this.ctx=this.elt.getContext('2d');this.imgcache={};}
Renderer.prototype.screenspace=function(x,y){return[((x-0.5)*this.elt.width)/8,((y-0.5)*this.elt.height)/8];};Renderer.prototype.boardspace=function(x,y){return[x*8/this.elt.width+0.5,y*8/this.elt.height+0.5];};Renderer.prototype.rect=function(x1,y1,x2,y2,style,alpha){var lrx,lry,ulx,uly,_ref,_ref1;if(alpha==null){alpha=1.0;}
this.ctx.globalAlpha=alpha;this.ctx.fillStyle=style;_ref=this.screenspace(x1,y1),ulx=_ref[0],uly=_ref[1];_ref1=this.screenspace(x2,y2),lrx=_ref1[0],lry=_ref1[1];return this.ctx.fillRect(ulx,uly,lrx-ulx,lry-uly);};Renderer.prototype.image=function(x,y,url,alpha){var elt,img,_ref;if(alpha==null){alpha=1.0;}
img=this.imgcache[url];if(img!=null){_ref=this.screenspace(x,y),x=_ref[0],y=_ref[1];this.ctx.globalAlpha=alpha;return this.ctx.drawImage(img,x-(img.width/2),y-(img.height/2));}else{elt=document.createElement('img');elt.src=url;return this.imgcache[url]=elt;}};Renderer.prototype.text=function(x,y,str){this.ctx.globalAlpha=1.0;this.ctx.fillStyle='#c00';this.ctx.font='italic bold 30px sans-serif';this.ctx.textBaseline='top';return this.ctx.fillText(str,x,y);};return Renderer;})();}).call(this);});require.define("/lib/game.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Board,COOLDOWN,Game,Move,Pieces,VELOCITY,_;Board=require('./board');Pieces=require('./pieces');Move=require('./move');_=require('underscore');VELOCITY=1.0/30.0;COOLDOWN=30*3;module.exports=Game=(function(){function Game(layout){var piece,type,typename,x,y;this.board=new Board();this.pieces=(function(){var _i,_len,_ref,_ref1,_results;_results=[];for(_i=0,_len=layout.length;_i<_len;_i++){_ref=layout[_i],typename=_ref.type,(_ref1=_ref.location,x=_ref1[0],y=_ref1[1]);type=Pieces[typename];piece=new type();this.board.at(x,y).piece=piece;piece.move_to(x,y);_results.push(piece);}
return _results;}).call(this);this.essential_pieces=_.where(this.pieces,{is_essential:true});this.victor=null;this.active_moves=[];this.stalest_move=this.current_tick=0;this.move_history=[];this.states=[];}
Game.prototype.move=function(piece,destination_cell,tick){var movelist,_ref,_this=this;if(tick==null){tick=this.current_tick;}
movelist=(_ref=this.move_history[tick])!=null?_ref:[];movelist.push([piece,destination_cell]);movelist=_.sortBy(movelist,function(_arg){var cell_idx,destination_cell,piece,piece_idx;piece=_arg[0],destination_cell=_arg[1];piece_idx=_.indexOf(_this.pieces,piece);cell_idx=((destination_cell.location.y-1)*8)+(destination_cell.location.x-1);return(piece_idx*64)+cell_idx;});this.move_history[tick]=movelist;return this.stalest_move=Math.min(this.stalest_move,tick);};Game.prototype.tick=function(){var target_tick;target_tick=this.current_tick+1;if(this.stalest_move<this.current_tick){this.restore_from_state(this.states[this.stalest_move]);this.current_tick=this.stalest_move;}
while(this.current_tick<target_tick){this.states[this.current_tick]=this.create_state();this.simulate();this.current_tick+=1;}
return this.stalest_move=this.current_tick;};Game.prototype.simulate=function(){var captured_piece,cell,destination_cell,finished_moves,move,p,piece,_i,_j,_k,_len,_len1,_len2,_ref,_ref1,_ref2,_ref3;if(this.move_history[this.current_tick]){_ref=this.move_history[this.current_tick];for(_i=0,_len=_ref.length;_i<_len;_i++){_ref1=_ref[_i],piece=_ref1[0],destination_cell=_ref1[1];cell=this.board.cell_of(piece);if(cell&&piece.valid_move(new Move(cell,destination_cell))){cell.piece=null;this.active_moves.push([piece,destination_cell]);piece.in_initial_location=false;}}}
finished_moves=[];_ref2=this.active_moves;for(_j=0,_len1=_ref2.length;_j<_len1;_j++){move=_ref2[_j];piece=move[0],destination_cell=move[1];if(piece.location.move_towards(destination_cell.location,VELOCITY)){captured_piece=destination_cell.piece;if(captured_piece){captured_piece.remove_from_play();}
destination_cell.piece=piece;finished_moves.push(move);piece.set_cooldown(COOLDOWN);}}
if(finished_moves.length>0){this.active_moves=_.difference(this.active_moves,finished_moves);}
_ref3=this.pieces;for(_k=0,_len2=_ref3.length;_k<_len2;_k++){piece=_ref3[_k];piece.tick_cooldown();}
p=_.find(this.essential_pieces,function(p){return!p.in_play();});if(p!=null){return this.victor=p.color==='black'?'white':'black';}};Game.prototype.create_state=function(){var c,p,x,y;return{victor:this.victor,active_moves:_.map(this.active_moves,_.clone),current_tick:this.current_tick,cells:(function(){var _i,_results;_results=[];for(x=_i=0;_i<8;x=++_i){_results.push((function(){var _j,_results1;_results1=[];for(y=_j=0;_j<8;y=++_j){c=this.board.at(x+1,y+1);if(c.piece){_results1.push(_.indexOf(this.pieces,c.piece));}else{_results1.push(null);}}
return _results1;}).call(this));}
return _results;}).call(this),pieces:(function(){var _i,_len,_ref,_results;_ref=this.pieces;_results=[];for(_i=0,_len=_ref.length;_i<_len;_i++){p=_ref[_i];_results.push(p.create_state());}
return _results;}).call(this)};};Game.prototype.restore_from_state=function(state){var c,pi,sc,x,y,_i,_j,_k,_ref,_results;this.victor=state.victor;this.active_moves=_.map(state.active_moves,_.clone);this.current_tick=state.current_tick;for(x=_i=0;_i<8;x=++_i){for(y=_j=0;_j<8;y=++_j){c=this.board.at(x+1,y+1);sc=state.cells[x][y];c.piece=sc!=null?this.pieces[sc]:null;}}
_results=[];for(pi=_k=0,_ref=state.pieces.length;0<=_ref?_k<_ref:_k>_ref;pi=0<=_ref?++_k:--_k){_results.push(this.pieces[pi].restore_from_state(state.pieces[pi]));}
return _results;};return Game;})();}).call(this);});require.define("/lib/board.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Board,Cell,Location;Cell=require('./cell');Location=require('./location');module.exports=Board=(function(){function Board(){var g,x,y,_i,_j,_k,_l;g=(function(){var _i,_results;_results=[];for(x=_i=0;_i<=9;x=++_i){_results.push((function(){var _j,_results1;_results1=[];for(y=_j=0;_j<=9;y=++_j){_results1.push(null);}
return _results1;})());}
return _results;})();for(x=_i=1;_i<=8;x=++_i){for(y=_j=1;_j<=8;y=++_j){g[x][y]=new Cell(new Location(x,y));}}
for(x=_k=1;_k<=8;x=++_k){for(y=_l=1;_l<=8;y=++_l){g[x][y].wire(g[x][y-1],g[x+1][y],g[x-1][y],g[x][y+1]);}}
this.grid=g;}
Board.prototype.at=function(x,y){var col;col=this.grid[x];return(col!=null)&&col[y];};Board.prototype.atloc=function(loc){return this.at(loc.x,loc.y);};Board.prototype.cell_of=function(piece){var cell;if(!piece.in_play()){return null;}
cell=this.at(piece.location.x,piece.location.y);if(!((cell!=null)&&cell.piece===piece)){return null;}
return cell;};return Board;})();}).call(this);});require.define("/lib/cell.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Cell,INVALID,dir,_i,_len,_ref;INVALID=null;module.exports=Cell=(function(){function Cell(location){this.location=location;if(this.location==null){throw new Error("no location provided");}
this.piece=null;this.valid=false;}
Cell.prototype.wire=function(n,e,w,s){var dir,_i,_len,_ref,_ref1;this.n=n;this.e=e;this.w=w;this.s=s;_ref=['n','e','w','s'];for(_i=0,_len=_ref.length;_i<_len;_i++){dir=_ref[_i];if((_ref1=this[dir])==null){this[dir]=INVALID;}}
return this.valid=true;};return Cell;})();INVALID=new Cell('invalid');_ref=['n','e','w','s'];for(_i=0,_len=_ref.length;_i<_len;_i++){dir=_ref[_i];INVALID[dir]=INVALID;}}).call(this);});require.define("/lib/location.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Location;module.exports=Location=(function(){function Location(x,y){this.x=x;this.y=y;if(!((this.x!=null)&&(this.y!=null))){throw new Error("Location ("+this.x+","+this.y+")? C'mon, son");}}
Location.prototype.gets=function(rhs){var _ref;return _ref=[rhs.x,rhs.y],this.x=_ref[0],this.y=_ref[1],_ref;};Location.prototype.move_towards=function(other_location,distance){var delta,dx,dy,_ref,_ref1,_ref2;_ref=[other_location.x-this.x,other_location.y-this.y],dx=_ref[0],dy=_ref[1];delta=Math.sqrt(dx*dx+dy*dy);if(delta<=distance){_ref1=[other_location.x,other_location.y],this.x=_ref1[0],this.y=_ref1[1];return true;}
_ref2=[this.x+(distance*dx)/delta,this.y+(distance*dy)/delta],this.x=_ref2[0],this.y=_ref2[1];return false;};return Location;})();}).call(this);});require.define("/lib/pieces/index.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){module.exports={BlackPawn:require('./black_pawn'),BlackRook:require('./black_rook'),BlackKnight:require('./black_knight'),BlackBishop:require('./black_bishop'),BlackQueen:require('./black_queen'),BlackKing:require('./black_king'),WhitePawn:require('./white_pawn'),WhiteRook:require('./white_rook'),WhiteKnight:require('./white_knight'),WhiteBishop:require('./white_bishop'),WhiteQueen:require('./white_queen'),WhiteKing:require('./white_king')};}).call(this);});require.define("/lib/pieces/black_pawn.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var BlackPawn,Pawn,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Pawn=require('./pawn');module.exports=BlackPawn=(function(_super){__extends(BlackPawn,_super);function BlackPawn(){return BlackPawn.__super__.constructor.apply(this,arguments);}
BlackPawn.prototype.color='black';BlackPawn.prototype.primary_direction='s';BlackPawn.prototype.img='img/black_pawn.png';return BlackPawn;})(Pawn);}).call(this);});require.define("/lib/pieces/pawn.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Pawn,Piece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Piece=require('../piece');module.exports=Pawn=(function(_super){__extends(Pawn,_super);function Pawn(){return Pawn.__super__.constructor.apply(this,arguments);}
Pawn.prototype.destinations=function(c){var double_forward,forward,possibly,rv;rv=[];forward=c[this.primary_direction];if(forward.piece==null){rv.push(forward);if(this.in_initial_location){double_forward=forward[this.primary_direction];if(double_forward.piece==null){rv.push(double_forward);}}}
possibly=function(c){if((c.piece!=null)&&c.piece.color!==this.color){return rv.push(c);}};possibly(forward.e);possibly(forward.w);return rv;};return Pawn;})(Piece);}).call(this);});require.define("/lib/piece.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Cooldown,Location,Move,Piece,_;Location=require('./location');Move=require('./move');Cooldown=require('./cooldown');_=require('underscore');module.exports=Piece=(function(){function Piece(){this.location=null;if(this.destinations==null){throw new Error("Please implement destinations");}
if(this.color==null){throw new Error("Please implement color");}}
Piece.prototype.in_play=function(){return this.location!=null;};Piece.prototype.move_to=function(x,y){return this.location=new Location(x,y);};Piece.prototype.set_cooldown=function(num_ticks){return this.cooldown=new Cooldown(num_ticks);};Piece.prototype.tick_cooldown=function(){var _ref;if((_ref=this.cooldown)!=null?_ref.tick():void 0){return this.cooldown=null;}};Piece.prototype.remove_from_play=function(){return this.location=null;};Piece.prototype.moves=function(from){var to,_i,_len,_ref,_results;_ref=this.destinations(from);_results=[];for(_i=0,_len=_ref.length;_i<_len;_i++){to=_ref[_i];if(this.valid_destination(to)){_results.push(new Move(from,to));}}
return _results;};Piece.prototype.valid_destination=function(dest){return(!(this.cooldown!=null))&&dest.valid&&(!(dest.piece!=null)||dest.piece.color!==this.color);};Piece.prototype.valid_move=function(move){return this.valid_destination(move.to)&&_.contains(this.destinations(move.from),move.to);};Piece.prototype.in_initial_location=true;Piece.prototype.create_state=function(){return[_.clone(this.location,this.in_initial_location,_.clone(this.cooldown))];};Piece.prototype.restore_from_state=function(state){this.location=_.clone(state[0]);this.in_initial_location=state[1];return this.cooldown=_.clone(state[2]);};return Piece;})();}).call(this);});require.define("/lib/move.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Move;module.exports=Move=(function(){function Move(from,to){this.from=from;this.to=to;if(!((this.from!=null)&&(this.to!=null))){throw new Error("Move ("+this.from+" -> "+this.to+")? I feel sorry for your mother");}
this.valid=this.from.valid&&this.to.valid;}
return Move;})();}).call(this);});require.define("/lib/cooldown.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Cooldown;module.exports=Cooldown=(function(){function Cooldown(initial){this.initial=initial;this.ticks_remaining=this.initial;}
Cooldown.prototype.tick=function(){return(this.ticks_remaining-=1)<=0;};Cooldown.prototype.fraction_remaining=function(){return Math.max(this.ticks_remaining,0)/this.initial;};return Cooldown;})();}).call(this);});require.define("/node_modules/underscore/package.json",function(require,module,exports,__dirname,__filename,process,global){module.exports={"main":"underscore.js"}});require.define("/node_modules/underscore/underscore.js",function(require,module,exports,__dirname,__filename,process,global){(function(){var root=this;var previousUnderscore=root._;var breaker={};var ArrayProto=Array.prototype,ObjProto=Object.prototype,FuncProto=Function.prototype;var push=ArrayProto.push,slice=ArrayProto.slice,concat=ArrayProto.concat,toString=ObjProto.toString,hasOwnProperty=ObjProto.hasOwnProperty;var
nativeForEach=ArrayProto.forEach,nativeMap=ArrayProto.map,nativeReduce=ArrayProto.reduce,nativeReduceRight=ArrayProto.reduceRight,nativeFilter=ArrayProto.filter,nativeEvery=ArrayProto.every,nativeSome=ArrayProto.some,nativeIndexOf=ArrayProto.indexOf,nativeLastIndexOf=ArrayProto.lastIndexOf,nativeIsArray=Array.isArray,nativeKeys=Object.keys,nativeBind=FuncProto.bind;var _=function(obj){if(obj instanceof _)return obj;if(!(this instanceof _))return new _(obj);this._wrapped=obj;};if(typeof exports!=='undefined'){if(typeof module!=='undefined'&&module.exports){exports=module.exports=_;}
exports._=_;}else{root._=_;}
_.VERSION='1.4.3';var each=_.each=_.forEach=function(obj,iterator,context){if(obj==null)return;if(nativeForEach&&obj.forEach===nativeForEach){obj.forEach(iterator,context);}else if(obj.length===+obj.length){for(var i=0,l=obj.length;i<l;i++){if(iterator.call(context,obj[i],i,obj)===breaker)return;}}else{for(var key in obj){if(_.has(obj,key)){if(iterator.call(context,obj[key],key,obj)===breaker)return;}}}};_.map=_.collect=function(obj,iterator,context){var results=[];if(obj==null)return results;if(nativeMap&&obj.map===nativeMap)return obj.map(iterator,context);each(obj,function(value,index,list){results[results.length]=iterator.call(context,value,index,list);});return results;};var reduceError='Reduce of empty array with no initial value';_.reduce=_.foldl=_.inject=function(obj,iterator,memo,context){var initial=arguments.length>2;if(obj==null)obj=[];if(nativeReduce&&obj.reduce===nativeReduce){if(context)iterator=_.bind(iterator,context);return initial?obj.reduce(iterator,memo):obj.reduce(iterator);}
each(obj,function(value,index,list){if(!initial){memo=value;initial=true;}else{memo=iterator.call(context,memo,value,index,list);}});if(!initial)throw new TypeError(reduceError);return memo;};_.reduceRight=_.foldr=function(obj,iterator,memo,context){var initial=arguments.length>2;if(obj==null)obj=[];if(nativeReduceRight&&obj.reduceRight===nativeReduceRight){if(context)iterator=_.bind(iterator,context);return initial?obj.reduceRight(iterator,memo):obj.reduceRight(iterator);}
var length=obj.length;if(length!==+length){var keys=_.keys(obj);length=keys.length;}
each(obj,function(value,index,list){index=keys?keys[--length]:--length;if(!initial){memo=obj[index];initial=true;}else{memo=iterator.call(context,memo,obj[index],index,list);}});if(!initial)throw new TypeError(reduceError);return memo;};_.find=_.detect=function(obj,iterator,context){var result;any(obj,function(value,index,list){if(iterator.call(context,value,index,list)){result=value;return true;}});return result;};_.filter=_.select=function(obj,iterator,context){var results=[];if(obj==null)return results;if(nativeFilter&&obj.filter===nativeFilter)return obj.filter(iterator,context);each(obj,function(value,index,list){if(iterator.call(context,value,index,list))results[results.length]=value;});return results;};_.reject=function(obj,iterator,context){return _.filter(obj,function(value,index,list){return!iterator.call(context,value,index,list);},context);};_.every=_.all=function(obj,iterator,context){iterator||(iterator=_.identity);var result=true;if(obj==null)return result;if(nativeEvery&&obj.every===nativeEvery)return obj.every(iterator,context);each(obj,function(value,index,list){if(!(result=result&&iterator.call(context,value,index,list)))return breaker;});return!!result;};var any=_.some=_.any=function(obj,iterator,context){iterator||(iterator=_.identity);var result=false;if(obj==null)return result;if(nativeSome&&obj.some===nativeSome)return obj.some(iterator,context);each(obj,function(value,index,list){if(result||(result=iterator.call(context,value,index,list)))return breaker;});return!!result;};_.contains=_.include=function(obj,target){if(obj==null)return false;if(nativeIndexOf&&obj.indexOf===nativeIndexOf)return obj.indexOf(target)!=-1;return any(obj,function(value){return value===target;});};_.invoke=function(obj,method){var args=slice.call(arguments,2);return _.map(obj,function(value){return(_.isFunction(method)?method:value[method]).apply(value,args);});};_.pluck=function(obj,key){return _.map(obj,function(value){return value[key];});};_.where=function(obj,attrs){if(_.isEmpty(attrs))return[];return _.filter(obj,function(value){for(var key in attrs){if(attrs[key]!==value[key])return false;}
return true;});};_.max=function(obj,iterator,context){if(!iterator&&_.isArray(obj)&&obj[0]===+obj[0]&&obj.length<65535){return Math.max.apply(Math,obj);}
if(!iterator&&_.isEmpty(obj))return-Infinity;var result={computed:-Infinity,value:-Infinity};each(obj,function(value,index,list){var computed=iterator?iterator.call(context,value,index,list):value;computed>=result.computed&&(result={value:value,computed:computed});});return result.value;};_.min=function(obj,iterator,context){if(!iterator&&_.isArray(obj)&&obj[0]===+obj[0]&&obj.length<65535){return Math.min.apply(Math,obj);}
if(!iterator&&_.isEmpty(obj))return Infinity;var result={computed:Infinity,value:Infinity};each(obj,function(value,index,list){var computed=iterator?iterator.call(context,value,index,list):value;computed<result.computed&&(result={value:value,computed:computed});});return result.value;};_.shuffle=function(obj){var rand;var index=0;var shuffled=[];each(obj,function(value){rand=_.random(index++);shuffled[index-1]=shuffled[rand];shuffled[rand]=value;});return shuffled;};var lookupIterator=function(value){return _.isFunction(value)?value:function(obj){return obj[value];};};_.sortBy=function(obj,value,context){var iterator=lookupIterator(value);return _.pluck(_.map(obj,function(value,index,list){return{value:value,index:index,criteria:iterator.call(context,value,index,list)};}).sort(function(left,right){var a=left.criteria;var b=right.criteria;if(a!==b){if(a>b||a===void 0)return 1;if(a<b||b===void 0)return-1;}
return left.index<right.index?-1:1;}),'value');};var group=function(obj,value,context,behavior){var result={};var iterator=lookupIterator(value||_.identity);each(obj,function(value,index){var key=iterator.call(context,value,index,obj);behavior(result,key,value);});return result;};_.groupBy=function(obj,value,context){return group(obj,value,context,function(result,key,value){(_.has(result,key)?result[key]:(result[key]=[])).push(value);});};_.countBy=function(obj,value,context){return group(obj,value,context,function(result,key){if(!_.has(result,key))result[key]=0;result[key]++;});};_.sortedIndex=function(array,obj,iterator,context){iterator=iterator==null?_.identity:lookupIterator(iterator);var value=iterator.call(context,obj);var low=0,high=array.length;while(low<high){var mid=(low+high)>>>1;iterator.call(context,array[mid])<value?low=mid+1:high=mid;}
return low;};_.toArray=function(obj){if(!obj)return[];if(_.isArray(obj))return slice.call(obj);if(obj.length===+obj.length)return _.map(obj,_.identity);return _.values(obj);};_.size=function(obj){if(obj==null)return 0;return(obj.length===+obj.length)?obj.length:_.keys(obj).length;};_.first=_.head=_.take=function(array,n,guard){if(array==null)return void 0;return(n!=null)&&!guard?slice.call(array,0,n):array[0];};_.initial=function(array,n,guard){return slice.call(array,0,array.length-((n==null)||guard?1:n));};_.last=function(array,n,guard){if(array==null)return void 0;if((n!=null)&&!guard){return slice.call(array,Math.max(array.length-n,0));}else{return array[array.length-1];}};_.rest=_.tail=_.drop=function(array,n,guard){return slice.call(array,(n==null)||guard?1:n);};_.compact=function(array){return _.filter(array,_.identity);};var flatten=function(input,shallow,output){each(input,function(value){if(_.isArray(value)){shallow?push.apply(output,value):flatten(value,shallow,output);}else{output.push(value);}});return output;};_.flatten=function(array,shallow){return flatten(array,shallow,[]);};_.without=function(array){return _.difference(array,slice.call(arguments,1));};_.uniq=_.unique=function(array,isSorted,iterator,context){if(_.isFunction(isSorted)){context=iterator;iterator=isSorted;isSorted=false;}
var initial=iterator?_.map(array,iterator,context):array;var results=[];var seen=[];each(initial,function(value,index){if(isSorted?(!index||seen[seen.length-1]!==value):!_.contains(seen,value)){seen.push(value);results.push(array[index]);}});return results;};_.union=function(){return _.uniq(concat.apply(ArrayProto,arguments));};_.intersection=function(array){var rest=slice.call(arguments,1);return _.filter(_.uniq(array),function(item){return _.every(rest,function(other){return _.indexOf(other,item)>=0;});});};_.difference=function(array){var rest=concat.apply(ArrayProto,slice.call(arguments,1));return _.filter(array,function(value){return!_.contains(rest,value);});};_.zip=function(){var args=slice.call(arguments);var length=_.max(_.pluck(args,'length'));var results=new Array(length);for(var i=0;i<length;i++){results[i]=_.pluck(args,""+i);}
return results;};_.object=function(list,values){if(list==null)return{};var result={};for(var i=0,l=list.length;i<l;i++){if(values){result[list[i]]=values[i];}else{result[list[i][0]]=list[i][1];}}
return result;};_.indexOf=function(array,item,isSorted){if(array==null)return-1;var i=0,l=array.length;if(isSorted){if(typeof isSorted=='number'){i=(isSorted<0?Math.max(0,l+isSorted):isSorted);}else{i=_.sortedIndex(array,item);return array[i]===item?i:-1;}}
if(nativeIndexOf&&array.indexOf===nativeIndexOf)return array.indexOf(item,isSorted);for(;i<l;i++)if(array[i]===item)return i;return-1;};_.lastIndexOf=function(array,item,from){if(array==null)return-1;var hasIndex=from!=null;if(nativeLastIndexOf&&array.lastIndexOf===nativeLastIndexOf){return hasIndex?array.lastIndexOf(item,from):array.lastIndexOf(item);}
var i=(hasIndex?from:array.length);while(i--)if(array[i]===item)return i;return-1;};_.range=function(start,stop,step){if(arguments.length<=1){stop=start||0;start=0;}
step=arguments[2]||1;var len=Math.max(Math.ceil((stop-start)/step),0);var idx=0;var range=new Array(len);while(idx<len){range[idx++]=start;start+=step;}
return range;};var ctor=function(){};_.bind=function(func,context){var args,bound;if(func.bind===nativeBind&&nativeBind)return nativeBind.apply(func,slice.call(arguments,1));if(!_.isFunction(func))throw new TypeError;args=slice.call(arguments,2);return bound=function(){if(!(this instanceof bound))return func.apply(context,args.concat(slice.call(arguments)));ctor.prototype=func.prototype;var self=new ctor;ctor.prototype=null;var result=func.apply(self,args.concat(slice.call(arguments)));if(Object(result)===result)return result;return self;};};_.bindAll=function(obj){var funcs=slice.call(arguments,1);if(funcs.length==0)funcs=_.functions(obj);each(funcs,function(f){obj[f]=_.bind(obj[f],obj);});return obj;};_.memoize=function(func,hasher){var memo={};hasher||(hasher=_.identity);return function(){var key=hasher.apply(this,arguments);return _.has(memo,key)?memo[key]:(memo[key]=func.apply(this,arguments));};};_.delay=function(func,wait){var args=slice.call(arguments,2);return setTimeout(function(){return func.apply(null,args);},wait);};_.defer=function(func){return _.delay.apply(_,[func,1].concat(slice.call(arguments,1)));};_.throttle=function(func,wait){var context,args,timeout,result;var previous=0;var later=function(){previous=new Date;timeout=null;result=func.apply(context,args);};return function(){var now=new Date;var remaining=wait-(now-previous);context=this;args=arguments;if(remaining<=0){clearTimeout(timeout);timeout=null;previous=now;result=func.apply(context,args);}else if(!timeout){timeout=setTimeout(later,remaining);}
return result;};};_.debounce=function(func,wait,immediate){var timeout,result;return function(){var context=this,args=arguments;var later=function(){timeout=null;if(!immediate)result=func.apply(context,args);};var callNow=immediate&&!timeout;clearTimeout(timeout);timeout=setTimeout(later,wait);if(callNow)result=func.apply(context,args);return result;};};_.once=function(func){var ran=false,memo;return function(){if(ran)return memo;ran=true;memo=func.apply(this,arguments);func=null;return memo;};};_.wrap=function(func,wrapper){return function(){var args=[func];push.apply(args,arguments);return wrapper.apply(this,args);};};_.compose=function(){var funcs=arguments;return function(){var args=arguments;for(var i=funcs.length-1;i>=0;i--){args=[funcs[i].apply(this,args)];}
return args[0];};};_.after=function(times,func){if(times<=0)return func();return function(){if(--times<1){return func.apply(this,arguments);}};};_.keys=nativeKeys||function(obj){if(obj!==Object(obj))throw new TypeError('Invalid object');var keys=[];for(var key in obj)if(_.has(obj,key))keys[keys.length]=key;return keys;};_.values=function(obj){var values=[];for(var key in obj)if(_.has(obj,key))values.push(obj[key]);return values;};_.pairs=function(obj){var pairs=[];for(var key in obj)if(_.has(obj,key))pairs.push([key,obj[key]]);return pairs;};_.invert=function(obj){var result={};for(var key in obj)if(_.has(obj,key))result[obj[key]]=key;return result;};_.functions=_.methods=function(obj){var names=[];for(var key in obj){if(_.isFunction(obj[key]))names.push(key);}
return names.sort();};_.extend=function(obj){each(slice.call(arguments,1),function(source){if(source){for(var prop in source){obj[prop]=source[prop];}}});return obj;};_.pick=function(obj){var copy={};var keys=concat.apply(ArrayProto,slice.call(arguments,1));each(keys,function(key){if(key in obj)copy[key]=obj[key];});return copy;};_.omit=function(obj){var copy={};var keys=concat.apply(ArrayProto,slice.call(arguments,1));for(var key in obj){if(!_.contains(keys,key))copy[key]=obj[key];}
return copy;};_.defaults=function(obj){each(slice.call(arguments,1),function(source){if(source){for(var prop in source){if(obj[prop]==null)obj[prop]=source[prop];}}});return obj;};_.clone=function(obj){if(!_.isObject(obj))return obj;return _.isArray(obj)?obj.slice():_.extend({},obj);};_.tap=function(obj,interceptor){interceptor(obj);return obj;};var eq=function(a,b,aStack,bStack){if(a===b)return a!==0||1/a==1/b;if(a==null||b==null)return a===b;if(a instanceof _)a=a._wrapped;if(b instanceof _)b=b._wrapped;var className=toString.call(a);if(className!=toString.call(b))return false;switch(className){case'[object String]':return a==String(b);case'[object Number]':return a!=+a?b!=+b:(a==0?1/a==1/b:a==+b);case'[object Date]':case'[object Boolean]':return+a==+b;case'[object RegExp]':return a.source==b.source&&a.global==b.global&&a.multiline==b.multiline&&a.ignoreCase==b.ignoreCase;}
if(typeof a!='object'||typeof b!='object')return false;var length=aStack.length;while(length--){if(aStack[length]==a)return bStack[length]==b;}
aStack.push(a);bStack.push(b);var size=0,result=true;if(className=='[object Array]'){size=a.length;result=size==b.length;if(result){while(size--){if(!(result=eq(a[size],b[size],aStack,bStack)))break;}}}else{var aCtor=a.constructor,bCtor=b.constructor;if(aCtor!==bCtor&&!(_.isFunction(aCtor)&&(aCtor instanceof aCtor)&&_.isFunction(bCtor)&&(bCtor instanceof bCtor))){return false;}
for(var key in a){if(_.has(a,key)){size++;if(!(result=_.has(b,key)&&eq(a[key],b[key],aStack,bStack)))break;}}
if(result){for(key in b){if(_.has(b,key)&&!(size--))break;}
result=!size;}}
aStack.pop();bStack.pop();return result;};_.isEqual=function(a,b){return eq(a,b,[],[]);};_.isEmpty=function(obj){if(obj==null)return true;if(_.isArray(obj)||_.isString(obj))return obj.length===0;for(var key in obj)if(_.has(obj,key))return false;return true;};_.isElement=function(obj){return!!(obj&&obj.nodeType===1);};_.isArray=nativeIsArray||function(obj){return toString.call(obj)=='[object Array]';};_.isObject=function(obj){return obj===Object(obj);};each(['Arguments','Function','String','Number','Date','RegExp'],function(name){_['is'+name]=function(obj){return toString.call(obj)=='[object '+name+']';};});if(!_.isArguments(arguments)){_.isArguments=function(obj){return!!(obj&&_.has(obj,'callee'));};}
if(typeof(/./)!=='function'){_.isFunction=function(obj){return typeof obj==='function';};}
_.isFinite=function(obj){return isFinite(obj)&&!isNaN(parseFloat(obj));};_.isNaN=function(obj){return _.isNumber(obj)&&obj!=+obj;};_.isBoolean=function(obj){return obj===true||obj===false||toString.call(obj)=='[object Boolean]';};_.isNull=function(obj){return obj===null;};_.isUndefined=function(obj){return obj===void 0;};_.has=function(obj,key){return hasOwnProperty.call(obj,key);};_.noConflict=function(){root._=previousUnderscore;return this;};_.identity=function(value){return value;};_.times=function(n,iterator,context){var accum=Array(n);for(var i=0;i<n;i++)accum[i]=iterator.call(context,i);return accum;};_.random=function(min,max){if(max==null){max=min;min=0;}
return min+(0|Math.random()*(max-min+1));};var entityMap={escape:{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#x27;','/':'&#x2F;'}};entityMap.unescape=_.invert(entityMap.escape);var entityRegexes={escape:new RegExp('['+_.keys(entityMap.escape).join('')+']','g'),unescape:new RegExp('('+_.keys(entityMap.unescape).join('|')+')','g')};_.each(['escape','unescape'],function(method){_[method]=function(string){if(string==null)return'';return(''+string).replace(entityRegexes[method],function(match){return entityMap[method][match];});};});_.result=function(object,property){if(object==null)return null;var value=object[property];return _.isFunction(value)?value.call(object):value;};_.mixin=function(obj){each(_.functions(obj),function(name){var func=_[name]=obj[name];_.prototype[name]=function(){var args=[this._wrapped];push.apply(args,arguments);return result.call(this,func.apply(_,args));};});};var idCounter=0;_.uniqueId=function(prefix){var id=''+++idCounter;return prefix?prefix+id:id;};_.templateSettings={evaluate:/<%([\s\S]+?)%>/g,interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var noMatch=/(.)^/;var escapes={"'":"'",'\\':'\\','\r':'r','\n':'n','\t':'t','\u2028':'u2028','\u2029':'u2029'};var escaper=/\\|'|\r|\n|\t|\u2028|\u2029/g;_.template=function(text,data,settings){settings=_.defaults({},settings,_.templateSettings);var matcher=new RegExp([(settings.escape||noMatch).source,(settings.interpolate||noMatch).source,(settings.evaluate||noMatch).source].join('|')+'|$','g');var index=0;var source="__p+='";text.replace(matcher,function(match,escape,interpolate,evaluate,offset){source+=text.slice(index,offset).replace(escaper,function(match){return'\\'+escapes[match];});if(escape){source+="'+\n((__t=("+escape+"))==null?'':_.escape(__t))+\n'";}
if(interpolate){source+="'+\n((__t=("+interpolate+"))==null?'':__t)+\n'";}
if(evaluate){source+="';\n"+evaluate+"\n__p+='";}
index=offset+match.length;return match;});source+="';\n";if(!settings.variable)source='with(obj||{}){\n'+source+'}\n';source="var __t,__p='',__j=Array.prototype.join,"+"print=function(){__p+=__j.call(arguments,'');};\n"+
source+"return __p;\n";try{var render=new Function(settings.variable||'obj','_',source);}catch(e){e.source=source;throw e;}
if(data)return render(data,_);var template=function(data){return render.call(this,data,_);};template.source='function('+(settings.variable||'obj')+'){\n'+source+'}';return template;};_.chain=function(obj){return _(obj).chain();};var result=function(obj){return this._chain?_(obj).chain():obj;};_.mixin(_);each(['pop','push','reverse','shift','sort','splice','unshift'],function(name){var method=ArrayProto[name];_.prototype[name]=function(){var obj=this._wrapped;method.apply(obj,arguments);if((name=='shift'||name=='splice')&&obj.length===0)delete obj[0];return result.call(this,obj);};});each(['concat','join','slice'],function(name){var method=ArrayProto[name];_.prototype[name]=function(){return result.call(this,method.apply(this._wrapped,arguments));};});_.extend(_.prototype,{chain:function(){this._chain=true;return this;},value:function(){return this._wrapped;}});}).call(this);});require.define("/lib/pieces/black_rook.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var BlackRook,Rook,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Rook=require('./rook');module.exports=BlackRook=(function(_super){__extends(BlackRook,_super);function BlackRook(){return BlackRook.__super__.constructor.apply(this,arguments);}
BlackRook.prototype.color='black';BlackRook.prototype.img='img/black_rook.png';return BlackRook;})(Rook);}).call(this);});require.define("/lib/pieces/rook.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Rook,WalkingPiece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};WalkingPiece=require('./walking_piece');module.exports=Rook=(function(_super){__extends(Rook,_super);function Rook(){return Rook.__super__.constructor.apply(this,arguments);}
Rook.prototype.destinations=function(c){var dir,rv,_i,_len,_ref;rv=[];_ref=[['n'],['e'],['w'],['s']];for(_i=0,_len=_ref.length;_i<_len;_i++){dir=_ref[_i];this.walk(c,dir,rv);}
return rv;};return Rook;})(WalkingPiece);}).call(this);});require.define("/lib/pieces/walking_piece.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Piece,WalkingPiece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Piece=require('../piece');module.exports=WalkingPiece=(function(_super){__extends(WalkingPiece,_super);function WalkingPiece(){return WalkingPiece.__super__.constructor.apply(this,arguments);}
WalkingPiece.prototype.walk=function(c,dirs,ax){var dir,_i,_len;for(_i=0,_len=dirs.length;_i<_len;_i++){dir=dirs[_i];c=c[dir];}
if(!c.valid){return;}
if(c.piece&&c.piece.color===this.color){return;}
ax.push(c);if(c.piece){return;}
return this.walk(c,dirs,ax);};return WalkingPiece;})(Piece);}).call(this);});require.define("/lib/pieces/black_knight.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var BlackKnight,Knight,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Knight=require('./knight');module.exports=BlackKnight=(function(_super){__extends(BlackKnight,_super);function BlackKnight(){return BlackKnight.__super__.constructor.apply(this,arguments);}
BlackKnight.prototype.color='black';BlackKnight.prototype.img='img/black_knight.png';return BlackKnight;})(Knight);}).call(this);});require.define("/lib/pieces/knight.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Knight,Piece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Piece=require('../piece');module.exports=Knight=(function(_super){__extends(Knight,_super);function Knight(){return Knight.__super__.constructor.apply(this,arguments);}
Knight.prototype.destinations=function(c){return[c.n.n.w,c.n.n.e,c.e.e.n,c.e.e.s,c.s.s.e,c.s.s.w,c.w.w.s,c.w.w.n];};return Knight;})(Piece);}).call(this);});require.define("/lib/pieces/black_bishop.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Bishop,BlackBishop,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Bishop=require('./bishop');module.exports=BlackBishop=(function(_super){__extends(BlackBishop,_super);function BlackBishop(){return BlackBishop.__super__.constructor.apply(this,arguments);}
BlackBishop.prototype.color='black';BlackBishop.prototype.img='img/black_bishop.png';return BlackBishop;})(Bishop);}).call(this);});require.define("/lib/pieces/bishop.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Bishop,WalkingPiece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};WalkingPiece=require('./walking_piece');module.exports=Bishop=(function(_super){__extends(Bishop,_super);function Bishop(){return Bishop.__super__.constructor.apply(this,arguments);}
Bishop.prototype.destinations=function(c){var dir,rv,_i,_len,_ref;rv=[];_ref=[['n','e'],['s','e'],['n','w'],['s','w']];for(_i=0,_len=_ref.length;_i<_len;_i++){dir=_ref[_i];this.walk(c,dir,rv);}
return rv;};return Bishop;})(WalkingPiece);}).call(this);});require.define("/lib/pieces/black_queen.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var BlackQueen,Queen,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Queen=require('./queen');module.exports=BlackQueen=(function(_super){__extends(BlackQueen,_super);function BlackQueen(){return BlackQueen.__super__.constructor.apply(this,arguments);}
BlackQueen.prototype.color='black';BlackQueen.prototype.img='img/black_queen.png';return BlackQueen;})(Queen);}).call(this);});require.define("/lib/pieces/queen.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Queen,WalkingPiece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};WalkingPiece=require('./walking_piece');module.exports=Queen=(function(_super){__extends(Queen,_super);function Queen(){return Queen.__super__.constructor.apply(this,arguments);}
Queen.prototype.destinations=function(c){var dir,rv,_i,_len,_ref;rv=[];_ref=[['n'],['e'],['w'],['s'],['n','e'],['s','e'],['n','w'],['s','w']];for(_i=0,_len=_ref.length;_i<_len;_i++){dir=_ref[_i];this.walk(c,dir,rv);}
return rv;};return Queen;})(WalkingPiece);}).call(this);});require.define("/lib/pieces/black_king.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var BlackKing,King,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};King=require('./king');module.exports=BlackKing=(function(_super){__extends(BlackKing,_super);function BlackKing(){return BlackKing.__super__.constructor.apply(this,arguments);}
BlackKing.prototype.color='black';BlackKing.prototype.img='img/black_king.png';return BlackKing;})(King);}).call(this);});require.define("/lib/pieces/king.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var King,Piece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Piece=require('../piece');module.exports=King=(function(_super){__extends(King,_super);function King(){return King.__super__.constructor.apply(this,arguments);}
King.prototype.destinations=function(c){return[c.n.w,c.n,c.n.e,c.w,c.e,c.s.w,c.s,c.s.e];};King.prototype.is_essential=true;return King;})(Piece);}).call(this);});require.define("/lib/pieces/white_pawn.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Pawn,WhitePawn,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Pawn=require('./pawn');module.exports=WhitePawn=(function(_super){__extends(WhitePawn,_super);function WhitePawn(){return WhitePawn.__super__.constructor.apply(this,arguments);}
WhitePawn.prototype.color='white';WhitePawn.prototype.primary_direction='n';WhitePawn.prototype.img='img/white_pawn.png';return WhitePawn;})(Pawn);}).call(this);});require.define("/lib/pieces/white_rook.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Rook,WhiteRook,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Rook=require('./rook');module.exports=WhiteRook=(function(_super){__extends(WhiteRook,_super);function WhiteRook(){return WhiteRook.__super__.constructor.apply(this,arguments);}
WhiteRook.prototype.color='white';WhiteRook.prototype.img='img/white_rook.png';return WhiteRook;})(Rook);}).call(this);});require.define("/lib/pieces/white_knight.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Knight,WhiteKnight,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Knight=require('./knight');module.exports=WhiteKnight=(function(_super){__extends(WhiteKnight,_super);function WhiteKnight(){return WhiteKnight.__super__.constructor.apply(this,arguments);}
WhiteKnight.prototype.color='white';WhiteKnight.prototype.img='img/white_knight.png';return WhiteKnight;})(Knight);}).call(this);});require.define("/lib/pieces/white_bishop.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Bishop,WhiteBishop,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Bishop=require('./bishop');module.exports=WhiteBishop=(function(_super){__extends(WhiteBishop,_super);function WhiteBishop(){return WhiteBishop.__super__.constructor.apply(this,arguments);}
WhiteBishop.prototype.color='white';WhiteBishop.prototype.img='img/white_bishop.png';return WhiteBishop;})(Bishop);}).call(this);});require.define("/lib/pieces/white_queen.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Queen,WhiteQueen,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Queen=require('./queen');module.exports=WhiteQueen=(function(_super){__extends(WhiteQueen,_super);function WhiteQueen(){return WhiteQueen.__super__.constructor.apply(this,arguments);}
WhiteQueen.prototype.color='white';WhiteQueen.prototype.img='img/white_queen.png';return WhiteQueen;})(Queen);}).call(this);});require.define("/lib/pieces/white_king.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var King,WhiteKing,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};King=require('./king');module.exports=WhiteKing=(function(_super){__extends(WhiteKing,_super);function WhiteKing(){return WhiteKing.__super__.constructor.apply(this,arguments);}
WhiteKing.prototype.color='white';WhiteKing.prototype.img='img/white_king.png';return WhiteKing;})(King);}).call(this);});require.define("/lib/displayboard.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var DisplayBoard;module.exports=DisplayBoard=(function(){function DisplayBoard(renderer){this.renderer=renderer;}
DisplayBoard.prototype.draw=function(){var style,x,y,_i,_results;_results=[];for(x=_i=1;_i<=8;x=++_i){_results.push((function(){var _j,_results1;_results1=[];for(y=_j=1;_j<=8;y=++_j){style=(x+y)%2===0?'white':'black';_results1.push(this.renderer.rect(x-0.5,y-0.5,x+0.5,y+0.5,style));}
return _results1;}).call(this));}
return _results;};return DisplayBoard;})();}).call(this);});require.define("/lib/layouts.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){module.exports={traditional:[{type:'BlackRook',location:[1,1]},{type:'BlackKnight',location:[2,1]},{type:'BlackBishop',location:[3,1]},{type:'BlackQueen',location:[4,1]},{type:'BlackKing',location:[5,1]},{type:'BlackBishop',location:[6,1]},{type:'BlackKnight',location:[7,1]},{type:'BlackRook',location:[8,1]},{type:'BlackPawn',location:[1,2]},{type:'BlackPawn',location:[2,2]},{type:'BlackPawn',location:[3,2]},{type:'BlackPawn',location:[4,2]},{type:'BlackPawn',location:[5,2]},{type:'BlackPawn',location:[6,2]},{type:'BlackPawn',location:[7,2]},{type:'BlackPawn',location:[8,2]},{type:'WhitePawn',location:[1,7]},{type:'WhitePawn',location:[2,7]},{type:'WhitePawn',location:[3,7]},{type:'WhitePawn',location:[4,7]},{type:'WhitePawn',location:[5,7]},{type:'WhitePawn',location:[6,7]},{type:'WhitePawn',location:[7,7]},{type:'WhitePawn',location:[8,7]},{type:'WhiteRook',location:[1,8]},{type:'WhiteKnight',location:[2,8]},{type:'WhiteBishop',location:[3,8]},{type:'WhiteQueen',location:[4,8]},{type:'WhiteKing',location:[5,8]},{type:'WhiteBishop',location:[6,8]},{type:'WhiteKnight',location:[7,8]},{type:'WhiteRook',location:[8,8]}]};}).call(this);});require.define("/client.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var DisplayGame;DisplayGame=require('./lib/displaygame');new DisplayGame(document.getElementById("board"));}).call(this);});require("/client.coffee");})();