(function(){var require=function(file,cwd){var resolved=require.resolve(file,cwd||'/');var mod=require.modules[resolved];if(!mod)throw new Error('Failed to resolve module '+file+', tried '+resolved);var cached=require.cache[resolved];var res=cached?cached.exports:mod();return res;};require.paths=[];require.modules={};require.cache={};require.extensions=[".js",".coffee",".json"];require._core={'assert':true,'events':true,'fs':true,'path':true,'vm':true};require.resolve=(function(){return function(x,cwd){if(!cwd)cwd='/';if(require._core[x])return x;var path=require.modules.path();cwd=path.resolve('/',cwd);var y=cwd||'/';if(x.match(/^(?:\.\.?\/|\/)/)){var m=loadAsFileSync(path.resolve(y,x))||loadAsDirectorySync(path.resolve(y,x));if(m)return m;}
var n=loadNodeModulesSync(x,y);if(n)return n;throw new Error("Cannot find module '"+x+"'");function loadAsFileSync(x){x=path.normalize(x);if(require.modules[x]){return x;}
for(var i=0;i<require.extensions.length;i++){var ext=require.extensions[i];if(require.modules[x+ext])return x+ext;}}
function loadAsDirectorySync(x){x=x.replace(/\/+$/,'');var pkgfile=path.normalize(x+'/package.json');if(require.modules[pkgfile]){var pkg=require.modules[pkgfile]();var b=pkg.browserify;if(typeof b==='object'&&b.main){var m=loadAsFileSync(path.resolve(x,b.main));if(m)return m;}
else if(typeof b==='string'){var m=loadAsFileSync(path.resolve(x,b));if(m)return m;}
else if(pkg.main){var m=loadAsFileSync(path.resolve(x,pkg.main));if(m)return m;}}
return loadAsFileSync(x+'/index');}
function loadNodeModulesSync(x,start){var dirs=nodeModulesPathsSync(start);for(var i=0;i<dirs.length;i++){var dir=dirs[i];var m=loadAsFileSync(dir+'/'+x);if(m)return m;var n=loadAsDirectorySync(dir+'/'+x);if(n)return n;}
var m=loadAsFileSync(x);if(m)return m;}
function nodeModulesPathsSync(start){var parts;if(start==='/')parts=[''];else parts=path.normalize(start).split('/');var dirs=[];for(var i=parts.length-1;i>=0;i--){if(parts[i]==='node_modules')continue;var dir=parts.slice(0,i+1).join('/')+'/node_modules';dirs.push(dir);}
return dirs;}};})();require.alias=function(from,to){var path=require.modules.path();var res=null;try{res=require.resolve(from+'/package.json','/');}
catch(err){res=require.resolve(from,'/');}
var basedir=path.dirname(res);var keys=(Object.keys||function(obj){var res=[];for(var key in obj)res.push(key);return res;})(require.modules);for(var i=0;i<keys.length;i++){var key=keys[i];if(key.slice(0,basedir.length+1)===basedir+'/'){var f=key.slice(basedir.length);require.modules[to+f]=require.modules[basedir+f];}
else if(key===basedir){require.modules[to]=require.modules[basedir];}}};(function(){var process={};var global=typeof window!=='undefined'?window:{};var definedProcess=false;require.define=function(filename,fn){if(!definedProcess&&require.modules.__browserify_process){process=require.modules.__browserify_process();definedProcess=true;}
var dirname=require._core[filename]?'':require.modules.path().dirname(filename);var require_=function(file){var requiredModule=require(file,dirname);var cached=require.cache[require.resolve(file,dirname)];if(cached&&cached.parent===null){cached.parent=module_;}
return requiredModule;};require_.resolve=function(name){return require.resolve(name,dirname);};require_.modules=require.modules;require_.define=require.define;require_.cache=require.cache;var module_={id:filename,filename:filename,exports:{},loaded:false,parent:null};require.modules[filename]=function(){require.cache[filename]=module_;fn.call(module_.exports,require_,module_,module_.exports,dirname,filename,process,global);module_.loaded=true;return module_.exports;};};})();require.define("path",function(require,module,exports,__dirname,__filename,process,global){function filter(xs,fn){var res=[];for(var i=0;i<xs.length;i++){if(fn(xs[i],i,xs))res.push(xs[i]);}
return res;}
function normalizeArray(parts,allowAboveRoot){var up=0;for(var i=parts.length;i>=0;i--){var last=parts[i];if(last=='.'){parts.splice(i,1);}else if(last==='..'){parts.splice(i,1);up++;}else if(up){parts.splice(i,1);up--;}}
if(allowAboveRoot){for(;up--;up){parts.unshift('..');}}
return parts;}
var splitPathRe=/^(.+\/(?!$)|\/)?((?:.+?)?(\.[^.]*)?)$/;exports.resolve=function(){var resolvedPath='',resolvedAbsolute=false;for(var i=arguments.length;i>=-1&&!resolvedAbsolute;i--){var path=(i>=0)?arguments[i]:process.cwd();if(typeof path!=='string'||!path){continue;}
resolvedPath=path+'/'+resolvedPath;resolvedAbsolute=path.charAt(0)==='/';}
resolvedPath=normalizeArray(filter(resolvedPath.split('/'),function(p){return!!p;}),!resolvedAbsolute).join('/');return((resolvedAbsolute?'/':'')+resolvedPath)||'.';};exports.normalize=function(path){var isAbsolute=path.charAt(0)==='/',trailingSlash=path.slice(-1)==='/';path=normalizeArray(filter(path.split('/'),function(p){return!!p;}),!isAbsolute).join('/');if(!path&&!isAbsolute){path='.';}
if(path&&trailingSlash){path+='/';}
return(isAbsolute?'/':'')+path;};exports.join=function(){var paths=Array.prototype.slice.call(arguments,0);return exports.normalize(filter(paths,function(p,index){return p&&typeof p==='string';}).join('/'));};exports.dirname=function(path){var dir=splitPathRe.exec(path)[1]||'';var isWindows=false;if(!dir){return'.';}else if(dir.length===1||(isWindows&&dir.length<=3&&dir.charAt(1)===':')){return dir;}else{return dir.substring(0,dir.length-1);}};exports.basename=function(path,ext){var f=splitPathRe.exec(path)[2]||'';if(ext&&f.substr(-1*ext.length)===ext){f=f.substr(0,f.length-ext.length);}
return f;};exports.extname=function(path){return splitPathRe.exec(path)[3]||'';};exports.relative=function(from,to){from=exports.resolve(from).substr(1);to=exports.resolve(to).substr(1);function trim(arr){var start=0;for(;start<arr.length;start++){if(arr[start]!=='')break;}
var end=arr.length-1;for(;end>=0;end--){if(arr[end]!=='')break;}
if(start>end)return[];return arr.slice(start,end-start+1);}
var fromParts=trim(from.split('/'));var toParts=trim(to.split('/'));var length=Math.min(fromParts.length,toParts.length);var samePartsLength=length;for(var i=0;i<length;i++){if(fromParts[i]!==toParts[i]){samePartsLength=i;break;}}
var outputParts=[];for(var i=samePartsLength;i<fromParts.length;i++){outputParts.push('..');}
outputParts=outputParts.concat(toParts.slice(samePartsLength));return outputParts.join('/');};});require.define("__browserify_process",function(require,module,exports,__dirname,__filename,process,global){var process=module.exports={};process.nextTick=(function(){var canSetImmediate=typeof window!=='undefined'&&window.setImmediate;var canPost=typeof window!=='undefined'&&window.postMessage&&window.addEventListener;if(canSetImmediate){return function(f){return window.setImmediate(f)};}
if(canPost){var queue=[];window.addEventListener('message',function(ev){if(ev.source===window&&ev.data==='browserify-tick'){ev.stopPropagation();if(queue.length>0){var fn=queue.shift();fn();}}},true);return function nextTick(fn){queue.push(fn);window.postMessage('browserify-tick','*');};}
return function nextTick(fn){setTimeout(fn,0);};})();process.title='browser';process.browser=true;process.env={};process.argv=[];process.binding=function(name){if(name==='evals')return(require)('vm')
else throw new Error('No such module. (Possibly not yet loaded)')};(function(){var cwd='/';var path;process.cwd=function(){return cwd};process.chdir=function(dir){if(!path)path=require('path');cwd=path.resolve(dir,cwd);};})();});require.define("/lib/displaygame.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var DisplayBoard,DisplayGame,DisplayPiece,Game,Layouts,Location,Pieces,Renderer,__bind=function(fn,me){return function(){return fn.apply(me,arguments);};};Renderer=require('./renderer');Game=require('./game');DisplayBoard=require('./displayboard');DisplayPiece=require('./displaypiece');Layouts=require('./layouts');Pieces=require('./pieces');Location=require('./location');module.exports=DisplayGame=(function(){function DisplayGame(elt){this.draw=__bind(this.draw,this);var piece,_i,_len,_ref,_this=this;this.game=new Game(Layouts.traditional);this.renderer=new Renderer(elt);this.board=new DisplayBoard(this.renderer);_ref=this.game.pieces;for(_i=0,_len=_ref.length;_i<_len;_i++){piece=_ref[_i];this.pieces=new DisplayPiece(piece);}
window.setInterval(this.draw,66);elt.addEventListener('mousemove',function(evt){var rect,x,y,_ref1,_ref2;rect=elt.getBoundingClientRect();_ref1=[evt.clientX-rect.left,evt.clientY-rect.top],x=_ref1[0],y=_ref1[1];_ref2=_this.renderer.boardspace(x,y),x=_ref2[0],y=_ref2[1];x=Math.max(Math.min(Math.round(x),8),1);y=Math.max(Math.min(Math.round(y),8),1);return _this.location=new Location(x,y);});elt.addEventListener('mouseout',function(evt){return _this.location=null;});}
DisplayGame.prototype.draw=function(){var p,_i,_len,_ref;this.board.draw();_ref=this.game.pieces;for(_i=0,_len=_ref.length;_i<_len;_i++){p=_ref[_i];if(p.in_play()){this.renderer.image(p.location.x,p.location.y,p.img);}}
if(this.location){return this.renderer.text(0,0,"Mouse is at "+this.location.x+", "+this.location.y);}};return DisplayGame;})();}).call(this);});require.define("/lib/renderer.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Renderer,__slice=[].slice;module.exports=Renderer=(function(){function Renderer(elt){this.elt=elt;this.ctx=this.elt.getContext('2d');this.imgcache={};}
Renderer.prototype.screenspace=function(x,y){return[((x-0.5)*this.elt.width)/8,((y-0.5)*this.elt.height)/8];};Renderer.prototype.boardspace=function(x,y){return[x*8/this.elt.width+0.5,y*8/this.elt.height+0.5];};Renderer.prototype.rect=function(x1,y1,x2,y2,style){var _ref;this.ctx.fillStyle=style;return(_ref=this.ctx).fillRect.apply(_ref,__slice.call(this.screenspace(x1,y1)).concat(__slice.call(this.screenspace(x2,y2))));};Renderer.prototype.image=function(x,y,url){var elt,img,_ref;img=this.imgcache[url];if(img!=null){_ref=this.screenspace(x,y),x=_ref[0],y=_ref[1];return this.ctx.drawImage(img,x-(img.width/2),y-(img.height/2));}else{elt=document.createElement('img');elt.src=url;return this.imgcache[url]=elt;}};Renderer.prototype.text=function(x,y,str){this.ctx.fillStyle='#c00';this.ctx.font='italic bold 30px sans-serif';this.ctx.textBaseline='top';return this.ctx.fillText(str,x,y);};return Renderer;})();}).call(this);});require.define("/lib/game.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Board,Game,Pieces;Board=require('./board');Pieces=require('./pieces');module.exports=Game=(function(){function Game(layout){var piece,type,typename,x,y,_i,_len,_ref;this.board=new Board();this.pieces=[];for(_i=0,_len=layout.length;_i<_len;_i++){_ref=layout[_i],x=_ref[0],y=_ref[1],typename=_ref[2];type=Pieces[typename];piece=new type();this.pieces.push(piece);this.board.at(x,y).piece=piece;piece.move_to(x,y);}}
return Game;})();}).call(this);});require.define("/lib/board.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Board,Cell;Cell=require('./cell');module.exports=Board=(function(){function Board(){var g,x,y,_i,_j,_k,_l;g=(function(){var _i,_results;_results=[];for(x=_i=0;_i<10;x=++_i){_results.push((function(){var _j,_results1;_results1=[];for(y=_j=0;_j<10;y=++_j){_results1.push(null);}
return _results1;})());}
return _results;})();for(x=_i=1;_i<=8;x=++_i){for(y=_j=1;_j<=8;y=++_j){g[x][y]=new Cell(x,y);}}
for(x=_k=1;_k<=8;x=++_k){for(y=_l=1;_l<=8;y=++_l){g[x][y].wire(g[x][y-1],g[x+1][y],g[x-1][y],g[x][y+1]);}}
this.grid=g;}
Board.prototype.at=function(x,y){return this.grid[x][y];};return Board;})();}).call(this);});require.define("/lib/cell.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Cell,INVALID,dir,_i,_len,_ref;INVALID=null;module.exports=Cell=(function(){function Cell(location){this.location=location;if(this.location==null){throw new Error("no location provided");}
this.piece=null;this.valid=false;}
Cell.prototype.wire=function(n,e,w,s){var dir,_i,_len,_ref,_ref1;this.n=n;this.e=e;this.w=w;this.s=s;_ref=['n','e','w','s'];for(_i=0,_len=_ref.length;_i<_len;_i++){dir=_ref[_i];if((_ref1=this[dir])==null){this[dir]=INVALID;}}
return this.valid=true;};return Cell;})();INVALID=new Cell('invalid');_ref=['n','e','w','s'];for(_i=0,_len=_ref.length;_i<_len;_i++){dir=_ref[_i];INVALID[dir]=INVALID;}}).call(this);});require.define("/lib/pieces/index.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){module.exports={BlackPawn:require('./black_pawn'),BlackRook:require('./black_rook'),BlackKnight:require('./black_knight'),BlackBishop:require('./black_bishop'),BlackQueen:require('./black_queen'),BlackKing:require('./black_king'),WhitePawn:require('./white_pawn'),WhiteRook:require('./white_rook'),WhiteKnight:require('./white_knight'),WhiteBishop:require('./white_bishop'),WhiteQueen:require('./white_queen'),WhiteKing:require('./white_king')};}).call(this);});require.define("/lib/pieces/black_pawn.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var BlackPawn,Piece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Piece=require('../piece');module.exports=BlackPawn=(function(_super){__extends(BlackPawn,_super);function BlackPawn(){return BlackPawn.__super__.constructor.apply(this,arguments);}
BlackPawn.prototype.color='black';BlackPawn.prototype.destinations=function(c){return[c.s];};BlackPawn.prototype.img='img/black_pawn.png';return BlackPawn;})(Piece);}).call(this);});require.define("/lib/piece.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Location,Move,Piece;Location=require('./location');Move=require('./move');module.exports=Piece=(function(){function Piece(){this.location=null;if(this.destinations==null){throw new Error("Please implement destinations");}
if(this.color==null){throw new Error("Please implement color");}}
Piece.prototype.in_play=function(){return this.location!=null;};Piece.prototype.move_to=function(x,y){return this.location=new Location(x,y);};Piece.prototype.remove_from_play=function(){return this.location=null;};Piece.prototype.moves=function(from){var to,_i,_len,_ref,_results;_ref=this.destinations(from);_results=[];for(_i=0,_len=_ref.length;_i<_len;_i++){to=_ref[_i];if(to.valid){_results.push(new Move(from,to));}}
return _results;};return Piece;})();}).call(this);});require.define("/lib/location.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Location;module.exports=Location=(function(){function Location(x,y){this.x=x;this.y=y;if(!((this.x!=null)&&(this.y!=null))){throw new Error("Location ("+this.x+","+this.y+")? C'mon, son");}}
Location.prototype.gets=function(rhs){var _ref;return _ref=[rhs.x,rhs.y],this.x=_ref[0],this.y=_ref[1],_ref;};return Location;})();}).call(this);});require.define("/lib/move.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Move;module.exports=Move=(function(){function Move(from,to){this.from=from;this.to=to;if(!((this.from!=null)&&(this.to!=null))){throw new Error("Move ("+this.from+" -> "+this.to+")? I feel sorry for your mother");}
this.valid=this.from.valid&&this.to.valid;}
return Move;})();}).call(this);});require.define("/lib/pieces/black_rook.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var BlackRook,Rook,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Rook=require('./rook');module.exports=BlackRook=(function(_super){__extends(BlackRook,_super);function BlackRook(){return BlackRook.__super__.constructor.apply(this,arguments);}
BlackRook.prototype.color='black';BlackRook.prototype.img='img/black_rook.png';return BlackRook;})(Rook);}).call(this);});require.define("/lib/pieces/rook.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Rook,WalkingPiece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};WalkingPiece=require('./walking_piece');module.exports=Rook=(function(_super){__extends(Rook,_super);function Rook(){return Rook.__super__.constructor.apply(this,arguments);}
Rook.prototype.destinations=function(c){var dir,rv,_i,_len,_ref;rv=[];_ref=[['n'],['e'],['w'],['s']];for(_i=0,_len=_ref.length;_i<_len;_i++){dir=_ref[_i];walk(c,dir,rv);}
return rv;};return Rook;})(WalkingPiece);}).call(this);});require.define("/lib/pieces/walking_piece.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Piece,WalkingPiece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Piece=require('../piece');module.exports=WalkingPiece=(function(_super){__extends(WalkingPiece,_super);function WalkingPiece(){return WalkingPiece.__super__.constructor.apply(this,arguments);}
WalkingPiece.prototype.walk=function(c,dirs,ax){var dir,_i,_len;for(_i=0,_len=dirs.length;_i<_len;_i++){dir=dirs[_i];c=c[dir];}
if(!c.valid){return;}
if(c.piece&&c.piece.color===this.color){return;}
ax.push(c);if(c.piece){return;}
return walk(c,dir,ax);};return WalkingPiece;})(Piece);}).call(this);});require.define("/lib/pieces/black_knight.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var BlackKnight,Knight,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Knight=require('./knight');module.exports=BlackKnight=(function(_super){__extends(BlackKnight,_super);function BlackKnight(){return BlackKnight.__super__.constructor.apply(this,arguments);}
BlackKnight.prototype.color='black';BlackKnight.prototype.img='img/black_knight.png';return BlackKnight;})(Knight);}).call(this);});require.define("/lib/pieces/knight.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Knight,Piece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Piece=require('../piece');module.exports=Knight=(function(_super){__extends(Knight,_super);function Knight(){return Knight.__super__.constructor.apply(this,arguments);}
Knight.prototype.destinations=function(c){return[c.n.n.w,c.n.n.e,c.e.e.n,c.e.e.s,c.s.s.e,c.s.s.w,c.w.w.s,c.w.w.n];};return Knight;})(Piece);}).call(this);});require.define("/lib/pieces/black_bishop.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Bishop,BlackBishop,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Bishop=require('./bishop');module.exports=BlackBishop=(function(_super){__extends(BlackBishop,_super);function BlackBishop(){return BlackBishop.__super__.constructor.apply(this,arguments);}
BlackBishop.prototype.color='black';BlackBishop.prototype.img='img/black_bishop.png';return BlackBishop;})(Bishop);}).call(this);});require.define("/lib/pieces/bishop.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Bishop,WalkingPiece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};WalkingPiece=require('./walking_piece');module.exports=Bishop=(function(_super){__extends(Bishop,_super);function Bishop(){return Bishop.__super__.constructor.apply(this,arguments);}
Bishop.prototype.destinations=function(c){var dir,rv,_i,_len,_ref;rv=[];_ref=[['n','e'],['s','e'],['n','w'],['s','w']];for(_i=0,_len=_ref.length;_i<_len;_i++){dir=_ref[_i];walk(c,dir,rv);}
return rv;};return Bishop;})(WalkingPiece);}).call(this);});require.define("/lib/pieces/black_queen.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var BlackQueen,Queen,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Queen=require('./queen');module.exports=BlackQueen=(function(_super){__extends(BlackQueen,_super);function BlackQueen(){return BlackQueen.__super__.constructor.apply(this,arguments);}
BlackQueen.prototype.color='black';BlackQueen.prototype.img='img/black_queen.png';return BlackQueen;})(Queen);}).call(this);});require.define("/lib/pieces/queen.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Queen,WalkingPiece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};WalkingPiece=require('./walking_piece');module.exports=Queen=(function(_super){__extends(Queen,_super);function Queen(){return Queen.__super__.constructor.apply(this,arguments);}
Queen.prototype.destinations=function(c){var dir,rv,_i,_len,_ref;rv=[];_ref=[['n'],['e'],['w'],['s'],['n','e'],['s','e'],['n','w'],['s','w']];for(_i=0,_len=_ref.length;_i<_len;_i++){dir=_ref[_i];walk(c,dir,rv);}
return rv;};return Queen;})(WalkingPiece);}).call(this);});require.define("/lib/pieces/black_king.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var BlackKing,King,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};King=require('./king');module.exports=BlackKing=(function(_super){__extends(BlackKing,_super);function BlackKing(){return BlackKing.__super__.constructor.apply(this,arguments);}
BlackKing.prototype.color='black';BlackKing.prototype.img='img/black_king.png';return BlackKing;})(King);}).call(this);});require.define("/lib/pieces/king.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var King,Piece,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Piece=require('../piece');module.exports=King=(function(_super){__extends(King,_super);function King(){return King.__super__.constructor.apply(this,arguments);}
King.prototype.destinations=function(c){return[c.n.w,c.n,c.n.e,c.w,c.e,c.s.w,c.s,c.s.e];};return King;})(Piece);}).call(this);});require.define("/lib/pieces/white_pawn.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Piece,WhitePawn,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Piece=require('../piece');module.exports=WhitePawn=(function(_super){__extends(WhitePawn,_super);function WhitePawn(){return WhitePawn.__super__.constructor.apply(this,arguments);}
WhitePawn.prototype.color='white';WhitePawn.prototype.destinations=function(c){return[c.n];};WhitePawn.prototype.img='img/white_pawn.png';return WhitePawn;})(Piece);}).call(this);});require.define("/lib/pieces/white_rook.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Rook,WhiteRook,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Rook=require('./rook');module.exports=WhiteRook=(function(_super){__extends(WhiteRook,_super);function WhiteRook(){return WhiteRook.__super__.constructor.apply(this,arguments);}
WhiteRook.prototype.color='white';WhiteRook.prototype.img='img/white_rook.png';return WhiteRook;})(Rook);}).call(this);});require.define("/lib/pieces/white_knight.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Knight,WhiteKnight,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Knight=require('./knight');module.exports=WhiteKnight=(function(_super){__extends(WhiteKnight,_super);function WhiteKnight(){return WhiteKnight.__super__.constructor.apply(this,arguments);}
WhiteKnight.prototype.color='white';WhiteKnight.prototype.img='img/white_knight.png';return WhiteKnight;})(Knight);}).call(this);});require.define("/lib/pieces/white_bishop.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Bishop,WhiteBishop,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Bishop=require('./bishop');module.exports=WhiteBishop=(function(_super){__extends(WhiteBishop,_super);function WhiteBishop(){return WhiteBishop.__super__.constructor.apply(this,arguments);}
WhiteBishop.prototype.color='white';WhiteBishop.prototype.img='img/white_bishop.png';return WhiteBishop;})(Bishop);}).call(this);});require.define("/lib/pieces/white_queen.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var Queen,WhiteQueen,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};Queen=require('./queen');module.exports=WhiteQueen=(function(_super){__extends(WhiteQueen,_super);function WhiteQueen(){return WhiteQueen.__super__.constructor.apply(this,arguments);}
WhiteQueen.prototype.color='white';WhiteQueen.prototype.img='img/white_queen.png';return WhiteQueen;})(Queen);}).call(this);});require.define("/lib/pieces/white_king.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var King,WhiteKing,__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))child[key]=parent[key];}function ctor(){this.constructor=child;}ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;};King=require('./king');module.exports=WhiteKing=(function(_super){__extends(WhiteKing,_super);function WhiteKing(){return WhiteKing.__super__.constructor.apply(this,arguments);}
WhiteKing.prototype.color='white';WhiteKing.prototype.img='img/white_king.png';return WhiteKing;})(King);}).call(this);});require.define("/lib/displayboard.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var DisplayBoard;module.exports=DisplayBoard=(function(){function DisplayBoard(renderer){this.renderer=renderer;}
DisplayBoard.prototype.draw=function(){var style,x,y,_i,_results;_results=[];for(x=_i=1;_i<=8;x=++_i){_results.push((function(){var _j,_results1;_results1=[];for(y=_j=1;_j<=8;y=++_j){style=(x+y)%2===0?'white':'black';_results1.push(this.renderer.rect(x-0.5,y-0.5,x+0.5,y+0.5,style));}
return _results1;}).call(this));}
return _results;};return DisplayBoard;})();}).call(this);});require.define("/lib/displaypiece.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var DisplayPiece;module.exports=DisplayPiece=(function(){function DisplayPiece(){}
return DisplayPiece;})();}).call(this);});require.define("/lib/layouts.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){module.exports={traditional:[[1,1,'BlackRook'],[2,1,'BlackKnight'],[3,1,'BlackBishop'],[4,1,'BlackQueen'],[5,1,'BlackKing'],[6,1,'BlackBishop'],[7,1,'BlackKnight'],[8,1,'BlackRook'],[1,2,'BlackPawn'],[2,2,'BlackPawn'],[3,2,'BlackPawn'],[4,2,'BlackPawn'],[5,2,'BlackPawn'],[6,2,'BlackPawn'],[7,2,'BlackPawn'],[8,2,'BlackPawn'],[1,7,'WhitePawn'],[2,7,'WhitePawn'],[3,7,'WhitePawn'],[4,7,'WhitePawn'],[5,7,'WhitePawn'],[6,7,'WhitePawn'],[7,7,'WhitePawn'],[8,7,'WhitePawn'],[1,8,'WhiteRook'],[2,8,'WhiteKnight'],[3,8,'WhiteBishop'],[4,8,'WhiteQueen'],[5,8,'WhiteKing'],[6,8,'WhiteBishop'],[7,8,'WhiteKnight'],[8,8,'WhiteRook']]};}).call(this);});require.define("/client.coffee",function(require,module,exports,__dirname,__filename,process,global){(function(){var DisplayGame;DisplayGame=require('./lib/displaygame');new DisplayGame(document.getElementById("board"));}).call(this);});require("/client.coffee");})();