global.Board = require "./lib/board"
require "./lib/cell"
require "./lib/cooldown"
require "./lib/displayboard"
require "./lib/displaygame"
require "./lib/displaypiece"
require "./lib/game"
require "./lib/layouts"
require "./lib/location"
require "./lib/move"
require "./lib/observer"
require "./lib/piece"
require "./lib/pieces"
require "./lib/player"
